AssrWeb/DjangoAssr/urls.py
from django.urls import path, include
from django.contrib import admin
from UploadSource.views import list_page_view

urlpatterns = [
    path("", list_page_view, name="index"),
    path("source/", include("UploadSource.urls")),
    path("dataset/", include("CreateDatasetApp.urls")),
    path("processing/", include("ProcessingApp.urls")),
    path("visual/", include("Visual.urls")),
    path('admin/', admin.site.urls),
]

AssrWeb/UploadSource/urls.py
from django.urls import path
from .views import (
    upload_page_view,
    upload_endpoint_view,
    filter_source_view,
    list_page_view,
    delete_view,
    search_source_by_string,
    Details_page,
)

app_name = "source"

urlpatterns = [
    path("new-source", upload_page_view, name="new-source"),
    path("source/search", search_source_by_string, name="search"),
    path("file", upload_endpoint_view, name="file-upload"),
    path("filter-source-list", filter_source_view, name="filter-source-list"),
    path("source-list", list_page_view, name="source-list"),
    path(
        "call-file/<int:metadata_id>",
        view=Details_page.as_view(),
        name="details"
    ),
    path("source-deletion/<int:metadata_id>", delete_view, name="delete"),
    path(
        "call-file/<int:metadata_id>",
        view=Details_page.as_view(),
        name="callajax"
    ),
]

AssrWeb/Visual/urls.py
from django.urls import path
from .api import visualization

app_name = "visual"

urlpatterns = [
    path(
        'results/<int:task_pk>/figures/',
        visualization.get_all_figures,
        name='get_figures'
    ),
    path(
        'results/<int:task_pk>/download-vis/',
        visualization.download_visualization,
        name='download-visualization'
    ),
]

AssrWeb/MetaCommon/models.py
from django.db import models
from django.core import validators
# Create your models here.


class Tags(models.Model):
    name = models.CharField(
        max_length=50,
        validators=[validators.MaxLengthValidator],
        unique=True
    )

    class Meta:
        abstract = True


class Metadata(models.Model):
    name = models.CharField(
        max_length=50,
        validators=[validators.MaxLengthValidator(50)]
    )
    author = models.CharField(
        max_length=50,
        validators=[validators.MaxLengthValidator(50)]
    )
    creationData = models.DateTimeField(
        auto_now_add=True,
        blank=True,
        verbose_name='Дата создания'
    )
    keyValue = models.JSONField()
    tag = models.ManyToManyField(Tags)

    class Meta:
        abstract = True


class TestingTagsModel(Tags):
    objects = models.Manager()


class TestingMetadataModel(Metadata):
    objects = models.Manager()
    tag = models.ManyToManyField(TestingTagsModel)


class DataFile(models.Model):
    """
        Abstract model to inheret common fields and methods\n
        from.
    """

    class Meta:
        abstract = True

    ancestorFile = models.BinaryField(
        verbose_name='Файл-прородитель'
    )
    metadata = models.OneToOneField(
        Metadata,
        on_delete=models.CASCADE,
        verbose_name='Метадата'
    )

    def __str__(self) -> None:
        return self.metadata.name


class TestingDataFile(DataFile):
    """
        Model to test DataFile abstract model
    """

    objects = models.Manager()
    metadata = models.OneToOneField(
        TestingMetadataModel,
        on_delete=models.CASCADE
    )

AssrWeb/UploadSource/models/source_file.py
from django.db import models
from MetaCommon.models import DataFile
from .source_file_meta import SourceMetadata


class SourceFile(DataFile):
    metadata = models.OneToOneField(
        SourceMetadata,
        null=True,
        on_delete=models.CASCADE,
        related_name='file'
    )

    class Meta:
        abstract = False
        db_table = "file"

AssrWeb/templates/SourceFiles/create.html
{% extends "base.html" %}
{% load static %}

{% block link %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/forms.css' %}">
{% endblock %}

{% block content %}
    <h3 class="header-text mt-2 mb-5">Загрузить файл-исходник</h3>
    <div class="container-fluid">
        <h2>Указать метаданные</h2>
        {% include "includes/metadataForm.html" %}
        <h2>Загрузить файлы</h2>
        {% include "includes/fileUploadForm.html" %}
        <button id="file-submit" class="w-100 btn btn-main main-text">
            Отправить
        </button>
        <script>
            const csrftoken = "{{ csrf_token }}";
        </script>
        <script type="module" src="{% static 'js/file/tag_socket.js' %}"></script>
    </div>
{% endblock %}

AssrWeb/templates/SourceFiles/details.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% load static %}

{% block link %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/forms.css' %}">
{% endblock %}

{% block content %}
    <h3 class="header-text mt-2 mb-5">Файл-исходник: {{ object.metadata.name }}</h3>
    <div class="container-fluid"> 
        <div class="d-flex bd-highlight align-items-center">
            <h2 class="me-auto p-2 bd-highlight">Метаданные</h2>
            <div class="d-flex bd-highlight">
                <button class="btn btn-main main-text ms-2 me-2 mb-2">Выгрузить</button>
                <a class="btn btn-danger main-text ms-2 me-2 mb-2" href="{% url 'source:delete' object.metadata.id %}">Удалить</a>
            </div>
        </div>
    </div> 
    <button class="btn btn-main main-text mb-1" type="button" data-bs-toggle="collapse" data-bs-target="#collapsed" aria-expanded="true">
        Свернуть
    </button>
    <div class="collapse show container-fluid frame-bg frame-pill" id="collapsed" aria-expanded="true">
        <div class="container-fluid d-flex flex-column px-2 py-2">
            <h5>Автор: {% if object.metadata.author|length != 0 %} {{ object.metadata.author }} {% else %} Нет автора {% endif %}</h5>
            <h5>Дата создания: {{ object.metadata.creationData}}</h5>
            <h5>Прочие свойства:</h5>
            <form class="metadata-changer">
                <div class="inline-container">
                    <div class="pos-rel" id="search-tags">
                            <button class="btn btn-main main-text" type="button" data-bs-toggle="collapse" data-bs-target="#tag-list" aria-expanded="false" aria-controls="tag-list">
                                Список тэгов
                            </button>
                            <div class="collapse" id="tag-list">
                                {% render_field form.tag class="px-2 searchable-tag" %}
                            </div>
                    </div>
                    <button class="btn main-text btn-primary" type="button">
                        Добавить теги
                    </button>
                </div>
                <div class="inline-container select-tags-cont ">
                    <div class="tags-list">Тэги:
                        {% for tag in object.metadata.tag.all %}
                            <label class="main-text deletable-tag tag-element">{{tag.name}}</label>
                        {% endfor %}
                    </div>
                </div>
                <table class="w-100 main-text frame-b"  id="id_keyValue">
                    <thead>
                        <tr class="frame-b">
                            <th class="align-center main-text frame-b">Ключ</th>
                            <th class="align-center main-text frame-b">Значение</th>
                        </tr>
                    </thead>
                    <tbody id="kv-append">
                        {% for key_value in key_value %}
                            <tr class="frame-b">
                                <td class="frame-b container-fluid w-50 px-0">
                                    <label class="kv-inputs w-100 main-text"> {{key_value.key}} </label>
                                </td>
                                <td class="frame-b container-fluid w-50 px-0">
                                    <label class="kv-inputs w-100 main-text"> {{key_value.value}} </label>
                                </td>
                            </tr>
                        {% endfor %}
                        <tr id="current-kv-row" class="frame-b">
                            <td class="frame-b container-fluid w-50 px-0">
                                <input type="text" class="kv-inputs w-100 main-text"> {{key_value.key}} </input>
                            </td>
                            <td class="frame-b container-fluid w-50 px-0">
                                <input type="text" class="kv-inputs w-100 main-text"> {{key_value.value}} </input>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </form>
        </div>
    </div>
    <h2 class="header-text mt-2 mb-5">Содержимый файл</h2>
    <div class="container-fluid frame-bg frame-pill ms-0 me-0">
        {% if data_type == "pdf" %}
            {{tableHeader|safe}}
        {% elif data_type == "csv" %}
            <table id = 'csv-table'>
                {{tableHeader|safe}}
                <tbody id = 'table-rows'>
                    {% csrf_token %}
                </tbody>
            </table>
            <button class="btn btn-main main-text ms-2 me-2 mb-2" onclick="getLastRow()" id = 'renderMore'>More data</button>
            <script type="module" src="{% static 'js/sourceFile/callajax.js' %}"></script>
        {% else %}
            <h1>Unknown type of data!</h1>
        {% endif %}
    </div>
{% endblock %}

AssrWeb/templates/SourceFiles/source-list.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% load static %}

{% block content %}
{% include "includes/listTemplate.html" %}
{% endblock %}