AssrWeb/CreateDatasetApp/urls.py
from django.urls import path
from CreateDatasetApp.views import *

app_name = "dataset"

urlpatterns = [
    path("new-dataset", create_view, name="new-source"),
    path("save", table_save_view, name="save"),
    path("table", table_view, name="table"),
    path("<int:dataset_pk>/save-source/", save_list_by_pk, name="save-source"),
    path("datasets-list", show_list, name="datasets-list"),
    # path(
    #     "datasets-list/<slug:dataset_slug>/",
    #     view_dataset,
    #     name="view_dataset"
    # ),
    path(
        "datasets-list/<slug:dataset_slug>/",
        Dataset_Details.as_view(),
        name="view_dataset"
    ),
    path("dataset-deletion/<slug:dataset_slug>/", delete_dataset, name='deletion'),
    path("datasets-list/<slug:dataset_slug>/edit_cell/", edit_cell, name="edit_cell"),
    path("datasets-list/<slug:dataset_slug>/remove_row/", remove_row, name="remove_row"),
    path("datasets-list/<slug:dataset_slug>/remove_column/", remove_column, name='remove_column'),
    path("datasets-list/<slug:dataset_slug>/import_from/", import_from, name="import_from"),
    path("datasets-list/<slug:dataset_slug>/new_line/", new_line, name="new_line"),
    path("datasets-list/<slug:dataset_slug>/remove_source/", delete_source, name="delete_source"),
    path("datasets-list/<slug:dataset_slug>/new_source/", new_source, name="new_source"),
    path("datasets-list/<slug:dataset_slug>/download/", dataset_download, name='dataset_download'),
    path("dataset/<slug:dataset_slug>/versions/", versions_list, name='versions_list'),
    path('version/<int:pk>/', version, name='version'),
    path('switch_version/<int:pk>/', switch_to_version, name='switch_to_version'),
    path("dataset/<slug:dataset_slug>/restore_init/", switch_to_init_version, name='restore_init'),
]

AssrWeb/DjangoAssr/urls.py
from django.urls import path, include
from django.contrib import admin
from UploadSource.views import list_page_view

urlpatterns = [
    path("", list_page_view, name="index"),
    path("source/", include("UploadSource.urls")),
    path("dataset/", include("CreateDatasetApp.urls")),
    path("processing/", include("ProcessingApp.urls")),
    path("visual/", include("Visual.urls")),
    path('admin/', admin.site.urls),
]

AssrWeb/Visual/urls.py
from django.urls import path
from .api import visualization

app_name = "visual"

urlpatterns = [
    path(
        'results/<int:task_pk>/figures/',
        visualization.get_all_figures,
        name='get_figures'
    ),
    path(
        'results/<int:task_pk>/download-vis/',
        visualization.download_visualization,
        name='download-visualization'
    ),
]

AssrWeb/MetaCommon/models.py
from django.db import models
from django.core import validators
# Create your models here.


class Tags(models.Model):
    name = models.CharField(
        max_length=50,
        validators=[validators.MaxLengthValidator],
        unique=True
    )

    class Meta:
        abstract = True


class Metadata(models.Model):
    name = models.CharField(
        max_length=50,
        validators=[validators.MaxLengthValidator(50)]
    )
    author = models.CharField(
        max_length=50,
        validators=[validators.MaxLengthValidator(50)]
    )
    creationData = models.DateTimeField(
        auto_now_add=True,
        blank=True,
        verbose_name='Дата создания'
    )
    keyValue = models.JSONField()
    tag = models.ManyToManyField(Tags)

    class Meta:
        abstract = True


class TestingTagsModel(Tags):
    objects = models.Manager()


class TestingMetadataModel(Metadata):
    objects = models.Manager()
    tag = models.ManyToManyField(TestingTagsModel)


class DataFile(models.Model):
    """
        Abstract model to inheret common fields and methods\n
        from.
    """

    class Meta:
        abstract = True

    ancestorFile = models.BinaryField(
        verbose_name='Файл-прородитель'
    )
    metadata = models.OneToOneField(
        Metadata,
        on_delete=models.CASCADE,
        verbose_name='Метадата'
    )

    def __str__(self) -> None:
        return self.metadata.name


class TestingDataFile(DataFile):
    """
        Model to test DataFile abstract model
    """

    objects = models.Manager()
    metadata = models.OneToOneField(
        TestingMetadataModel,
        on_delete=models.CASCADE
    )

AssrWeb/CreateDatasetApp/views/dataset_view.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator
from django.db.models import Value
from django.http import HttpResponse
from django.db.models import Q
from json import loads
from django.http import StreamingHttpResponse
from django.views import View

from CreateDatasetApp.forms import DatasetMetadataForm, DatasetSearchForm
from CreateDatasetApp.models import DatasetFile, DatasetMetadata, DatasetTags
from MetaCommon.ContentCreator import ContentCreator


def show_list(request):
    search_form = DatasetSearchForm()
    search_query = request.GET.get('search_query', None)
    context = {
        'form': search_form,
        'page': 'Датасеты',
        'create_name': "Датасет",
        'link': 'dataset:view_dataset',
        'addition_link': "dataset:new-source",
    }
    selected_tags = request.GET.getlist('tag')
    if search_query is None and len(selected_tags) == 0:
        all_datasets = DatasetMetadata.objects.order_by('name')
        paginator = Paginator(all_datasets, 8)
    else:
        search_result = DatasetMetadata.objects.filter(Q(name__contains=search_query))
        if search_query is not None and len(selected_tags) != 0:
            selected_tags = [i for i in DatasetTags.objects.filter(Q(pk__in=selected_tags))]
            search_result = DatasetMetadata.objects.filter(Q(name__contains=search_query) & Q(tag__in=selected_tags))
        paginator = Paginator(search_result, 8)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context['page_obj'] = page_obj
    return render(request, "Datasets/dataset-list.html", context)


def dataset_download(request, dataset_slug):
    csv_file = get_object_or_404(DatasetFile, id=dataset_slug)
    response = HttpResponse(csv_file.currentFile, content_type='text/csv')
    response['Content-Disposition'] = f'attachment; filename="{csv_file.metadata.name}.csv"'
    return response


class Dataset_Details(View):
    """CBV for dataset page"""
    render_step = 100  # hardcoded value of number of rows to be send

    def get_dataset_file(self, metadata_pk):
        dataset = DatasetFile.objects.filter(
            metadata__pk=metadata_pk
        ).get()
        file = dataset.currentFile
        return dataset, file

    def post(self, request, *args, **kwargs):
        data = loads(request.body)
        rows = int(data['last-row'])

        _, file = self.get_dataset(kwargs['dataset_slug'])
        cc = ContentCreator([file])

        return StreamingHttpResponse(
            cc.getNRows(rows, self.render_step),
            content_type='text/event-stream'
        )

    def get(self, request, *args, **kwargs):
        dataset, file = self.get_dataset_file(kwargs['dataset_slug'])
        key_values = []
        for i in dataset.metadata.keyValue.keys():
            key_values.append(
                {"key": i, "value": dataset.metadata.keyValue[i]}
            )
        html_info = ContentCreator([file])
        context = {
            'form': DatasetMetadataForm(),
            'object': dataset,
            'key_value': key_values,
            'tableHeader': html_info.getHeader(),
            'source_files': dataset.source_list.all().annotate(
                checked=Value(True)
            ),
            "data_type": html_info.type
        }

        return render(request, "Datasets/dataset-view.html", context)

AssrWeb/CreateDatasetApp/views/versions.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from CreateDatasetApp.models import Transaction, DatasetFile
from .utils import _apply_transaction

def versions_list(request, dataset_slug):
    dataset = get_object_or_404(DatasetFile, metadata__pk=dataset_slug)
    transactions = Transaction.objects.filter(dataset=dataset).order_by('-timestamp')
    return render(request, 'Datasets/versions.html', {
        'transactions': transactions,
        'dataset': dataset
    })

def version(request, pk):
    transaction = get_object_or_404(Transaction, pk=pk)
    return render(request, 'Datasets/version-detail.html', {'transaction': transaction})

def switch_to_version(request, pk):
    if pk==-1:
        dataset.source_list.set(dataset.ancestor_list.all())
        dataset.currentFile = dataset.ancestorFile
        dataset.save()
        return redirect('dataset:view_dataset', dataset_slug=dataset.metadata.pk)
    target_transaction = get_object_or_404(Transaction, pk=pk)
    dataset = target_transaction.dataset

    try:
        dataset.source_list.set(dataset.ancestor_list.all())
        dataset.currentFile = dataset.ancestorFile
        dataset.save()

        transactions = Transaction.objects.filter(
            dataset=dataset,
            timestamp__lte=target_transaction.timestamp
        ).order_by('timestamp')

        for transaction in transactions:
            _apply_transaction(transaction, dataset, save_transaction=False)

        return redirect('dataset:view_dataset', dataset_slug=dataset.metadata.pk)

    except Exception as e:
        return HttpResponse(f"Ошибка восстановления: {str(e)}", status=500)
    
def switch_to_init_version(request, dataset_slug):
    dataset = get_object_or_404(DatasetFile, metadata__pk=dataset_slug)
    try:

        dataset.source_list.set(dataset.ancestor_list.all())
        dataset.currentFile = dataset.ancestorFile
        dataset.save()
        return redirect('dataset:view_dataset', dataset_slug=dataset_slug)
        
    except Exception as e:
        return HttpResponse(f"Ошибка восстановления: {str(e)}", status=500)

AssrWeb/templates/Datasets/create.html
{% extends "base.html" %}
{% load static %}

{% block link %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/forms.css' %}">
{% endblock %}

{% block content %}
    <h3 class="header-text mt-2 mb-5">Создать датасет</h3>
    <div class="container-fluid">
        <h2>Указать метаданные</h2>
        {% include "includes/metadataForm.html" %}
        <h2>Выбрать исходники</h2>
        {% include "includes/sourceListView.html" %}
        <button id="load-preview" class="w-100 btn btn-main main-text">
            Предпросмотр
        </button>
        <div id="preview-table" class="container-fluid frame-bg frame-pill frame-overflow px-2 py-3 my-3">
            <div class="d-flex justify-content-center main-text">
                <p>Здесь вы сможете увидеть таблицу, сохраняемую в качестве датасета</p>
            </div>
        </div>
        <button id="send-dataset" class="w-100 btn btn-main main-text">
            Отправить
        </button>
        <script>
            const csrftoken = "{{ csrf_token }}";
        </script>
        <script type="module" src="{% static 'js/dataset/dataset_form.js' %}"></script>
        <script type="module" src="{% static 'js/dataset/tag_socket.js' %}"></script>
    </div>
{% endblock %}

AssrWeb/templates/Datasets/dataset-list.html
{% extends "base.html" %}
{% load static %}
{% block content %}
{% include "includes/listTemplate.html" %}
{% endblock %}

AssrWeb/templates/Datasets/dataset-view.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% load static %}

{% block link %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/forms.css' %}">
    <script type="module" src="{% static 'js/dataset/crud/edit_cells.js' %}"></script>
    <script type="module" src="{% static 'js/dataset/crud/delete_rows_cols.js' %}"></script>
{% endblock %}

{% block content %}
    <div id="dataset-id-div" data-dataset_id="{{object.pk}}"></div>
    <h3 class="header-text mt-2 mb-3">Датасет: {{ object.metadata.name }}</h3>
    <h5 class="main-text">
        Версия: {% if object.transactions.last.pk %} {{object.transactions.last.pk}}
        {% else %}
        Init
        {% endif %}
    </h5>
    <div class="container-fluid">
        <div class="d-flex bd-highlight align-items-center">
            <h2 class="me-auto p-2 bd-highlight">Метаданные</h2>
            <div class="d-flex bd-highlight">
                <a  class="btn btn-main main-text ms-2 me-2 mb-2" href="{% url 'dataset:versions_list' object.pk %}" >Просмотреть историю версий </a>
            </div>
        </div>
    </div>
    <button class="btn btn-main main-text mb-1" type="button" data-bs-toggle="collapse" data-bs-target="#collapsed" aria-expanded="true">
        Свернуть
    </button>
    <div class="collapse show container-fluid frame-bg frame-pill" id="collapsed" aria-expanded="true">
        <div class="container-fluid d-flex flex-column px-2 py-2">
            <h5>Автор: {{object.metadata.author}}</h5>
            <h5>Дата создания: {{ object.metadata.creationData}}</h5>
            <h5>Прочие свойства:</h5>
            <form class="metadata-changer">
                <div class="inline-container">
                    <div class="pos-rel" id="search-tags">
                            <button class="btn btn-main main-text" type="button" data-bs-toggle="collapse" data-bs-target="#tag-list" aria-expanded="false" aria-controls="tag-list">
                                Список тэгов
                            </button>
                            <div class="collapse" id="tag-list">
                                {% render_field form.tag class="px-2 searchable-tag" %}
                            </div>
                    </div>
                    <button class="btn main-text btn-primary" type="button">
                        Добавить теги
                    </button>
                </div>
                <div class="inline-container select-tags-cont ">
                    <div class="tags-list">Тэги:
                        {% for tag in object.metadata.tag.all %}
                            <label class="main-text deletable-tag tag-element">{{tag.name}}</label>
                        {% endfor %}
                    </div>
                </div>
                <table class="w-100 main-text frame-b"  id="id_keyValue">
                    <thead>
                        <tr class="frame-b">
                            <th class="align-center main-text frame-b">Ключ</th>
                            <th class="align-center main-text frame-b">Значение</th>
                        </tr>
                    </thead>
                    <tbody id="kv-append">
                        {% for key_value in key_value %}
                            <tr class="frame-b">
                                <td class="frame-b container-fluid w-50 px-0">
                                    <label class="kv-inputs w-100 main-text"> {{key_value.key}} </label>
                                </td>
                                <td class="frame-b container-fluid w-50 px-0">
                                    <label class="kv-inputs w-100 main-text"> {{key_value.value}} </label>
                                </td>
                            </tr>
                        {% endfor %}
                        <tr id="current-kv-row" class="frame-b">
                            <td class="frame-b container-fluid w-50 px-0">
                                <input type="text" class="kv-inputs w-100 main-text"> {{key_value.key}} </input>
                            </td>
                            <td class="frame-b container-fluid w-50 px-0">
                                <input type="text" class="kv-inputs w-100 main-text"> {{key_value.value}} </input>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </form>
        </div>
    </div>
    <h2 class="header-text mt-2 mb-3">Датасет</h2>
    <div class="container-fluid frame-bg frame-pill" >
        <div id="file-list">
            {% include "includes/sourceListView.html" %}
        </div>
        <div class="d-flex justify-content-around mt-2 mb-2">
            <button class="btn main-text btn-primary" type="button" id="source-list-update">
                Обновить датасет
            </button>
        </div>
        <div class="d-flex justify-content-around mt-2 mb-2">
            <button class="btn main-text btn-primary" type="button">
                Скачать датасет
            </button>
            <a class="btn main-text btn-danger" href="{% url 'dataset:deletion' object.metadata.pk %}">
                Удалить датасет
            </a>
        </div>
        <button class="btn btn-main main-text w-100 my-4" type="button" data-bs-toggle="collapse" data-bs-target="#table-ops" aria-expanded="false" aria-controls="table-ops">
            Табличные операции (опасно)
        </button>
        <div class="collapse" id="table-ops">
            <div class="d-flex justify-content-around mt-2 mb-2">
                <button class="btn main-text btn-primary" type="button">
                        Импортировать записи из
                </button>
                <button class="btn main-text btn-danger" type="button" id="delete-rows-btn">
                        Удалить записи
                </button>
                <button class="btn main-text btn-danger" type="button"  id="delete-cols-btn">
                        Удалить столбцы
                </button>
            </div>
            <div id="table-container" style="max-height: 500px; overflow-y: auto;"> 
                {% if data_type == "pdf" %}
                    {{tableHeader|safe}}
                {% elif data_type == "csv" %}
                    <table id = 'csv-table'>
                        {{tableHeader|safe}}
                        <tbody id = 'table-rows'>
                            {% csrf_token %}
                        </tbody>
                    </table>
                    <button class="btn btn-main main-text ms-2 me-2 mb-2" onclick="getLastRow()" id = 'renderMore'>More data</button>
                    <script type="module" src="{% static 'js/sourceFile/callajax.js' %}"></script>
                {% else %}
                    <h1>Unknown type of data!</h1>
                {% endif %}
            </div>
        </div>
    </div>
    <script>
        const csrftoken = "{{ csrf_token }}";
    </script>
{% endblock %}

AssrWeb/templates/Datasets/version-detail.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h2>Версия от {{ transaction.timestamp|date:"d.m.Y H:i" }}</h2>
    
    <div class="card" style="background-color: #5B525F;">
        <div class="card-body">
            <h5 class="card-title">Детали изменения</h5>
            
            <dl class="row">
                <dt class="col-sm-3">Тип операции:</dt>
                <dd class="col-sm-9">{{ transaction.get_transaction_type_display }}</dd>

                <dt class="col-sm-3">Направление:</dt>
                <dd class="col-sm-9">{{ transaction.get_transaction_direction_display }}</dd>

                <dt class="col-sm-3">Локация:</dt>
                <dd class="col-sm-9"><pre>{{ transaction.location|default:"-" }}</pre></dd>

                <dt class="col-sm-3">Данные:</dt>
                <dd class="col-sm-9"><pre>{{ transaction.data|default:"-" }}</pre></dd>

                <dt class="col-sm-3">Описание:</dt>
                <dd class="col-sm-9">{{ transaction.description|default:"-" }}</dd>
            </dl>
        </div>
    </div>

    <div class="mt-4">
        <a href="{% url 'dataset:versions_list' transaction.dataset.metadata.pk %}" class="btn btn-secondary">
            К списку версий
        </a>
        <a href="{% url 'dataset:switch_to_version' transaction.pk %}" class="btn btn-secondary">
            Восстановить версию
        </a>
    </div>
</div>
{% endblock %}

AssrWeb/templates/Datasets/versions.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h2 class="my-4 text-white">История изменений: {{ dataset.metadata.name }}</h2>
    
    <table class="table table-hover" style="background-color: #5B525F; color: white;">
        <thead style="background-color: #5B525F;">
            <tr>
                <th>Дата изменения</th>
                <th>Тип операции</th>
                <th>Описание</th>
                <th>Действия</th>
            </tr>
        </thead>
        <tbody>
            {% for transaction in transactions %}
            <tr>
                <td>{{ transaction.timestamp|date:"d.m.Y H:i" }}</td>
                <td>{{ transaction.get_transaction_type_display }}</td>
                <td>{{ transaction.description|default:"-" }}</td>
                <td>
                    <a href="{% url 'dataset:version' transaction.pk %}" 
                       class="btn btn-sm btn-info text-dark">
                        Подробнее
                    </a>
                </td>
            </tr>
            {% empty %}
            <tr>
                <td colspan="4" class="text-center text-white">
                    Нет записей об изменениях
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    
    <a href="{% url 'dataset:view_dataset' dataset.pk %}" class="btn btn-secondary">
        Назад к датасету
    </a>
    <a href="{% url 'dataset:restore_init' dataset.pk %}" class="btn btn-secondary">
        Возврат к Init
    </a>
</div>
{% endblock %}