AssrWeb/CreateDatasetApp/urls.py
from django.urls import path
from CreateDatasetApp.views import *

app_name = "dataset"

urlpatterns = [
    path("new-dataset", create_view, name="new-source"),
    path("save", table_save_view, name="save"),
    path("table", table_view, name="table"),
    path("<int:dataset_pk>/save-source/", save_list_by_pk, name="save-source"),
    path("datasets-list", show_list, name="datasets-list"),
    # path(
    #     "datasets-list/<slug:dataset_slug>/",
    #     view_dataset,
    #     name="view_dataset"
    # ),
    path(
        "datasets-list/<slug:dataset_slug>/",
        Dataset_Details.as_view(),
        name="view_dataset"
    ),
    path("dataset-deletion/<slug:dataset_slug>/", delete_dataset, name='deletion'),
    path("datasets-list/<slug:dataset_slug>/edit_cell/", edit_cell, name="edit_cell"),
    path("datasets-list/<slug:dataset_slug>/remove_row/", remove_row, name="remove_row"),
    path("datasets-list/<slug:dataset_slug>/remove_column/", remove_column, name='remove_column'),
    path("datasets-list/<slug:dataset_slug>/import_from/", import_from, name="import_from"),
    path("datasets-list/<slug:dataset_slug>/new_line/", new_line, name="new_line"),
    path("datasets-list/<slug:dataset_slug>/remove_source/", delete_source, name="delete_source"),
    path("datasets-list/<slug:dataset_slug>/new_source/", new_source, name="new_source"),
    path("datasets-list/<slug:dataset_slug>/download/", dataset_download, name='dataset_download'),
    path("dataset/<slug:dataset_slug>/versions/", versions_list, name='versions_list'),
    path('version/<int:pk>/', version, name='version'),
    path('switch_version/<int:pk>/', switch_to_version, name='switch_to_version'),
    path("dataset/<slug:dataset_slug>/restore_init/", switch_to_init_version, name='restore_init'),
]

AssrWeb/DjangoAssr/urls.py
from django.urls import path, include
from django.contrib import admin
from UploadSource.views import list_page_view

urlpatterns = [
    path("", list_page_view, name="index"),
    path("source/", include("UploadSource.urls")),
    path("dataset/", include("CreateDatasetApp.urls")),
    path("processing/", include("ProcessingApp.urls")),
    path("visual/", include("Visual.urls")),
    path('admin/', admin.site.urls),
]

AssrWeb/ProcessingApp/urls.py
from django.urls import path

from ProcessingApp.views import (
    List_Result_View,
    Guide_view,
    AcceptTaskView,
    task_results,
    download_processing_results
)

app_name = "processing"

urlpatterns = [
    path("new-process/", AcceptTaskView.as_view(), name="new-process"),
    path("view/<slug:task_pk>/", task_results, name="view"),
    path("view/<slug:task_pk>/download/", download_processing_results, name="download"),
    path("tasks/", List_Result_View.as_view(), name="task-list"),
    path("guide/", Guide_view.as_view(), name="guide"),
]

AssrWeb/Visual/urls.py
from django.urls import path
from .api import visualization

app_name = "visual"

urlpatterns = [
    path(
        'results/<int:task_pk>/figures/',
        visualization.get_all_figures,
        name='get_figures'
    ),
    path(
        'results/<int:task_pk>/download-vis/',
        visualization.download_visualization,
        name='download-visualization'
    ),
]

AssrWeb/ProcessingApp/views/guide_view.py
from django.views.generic import TemplateView


class Guide_view(TemplateView):
    template_name = 'Proccessing/guide.html'

AssrWeb/templates/Proccessing/create.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}

{% block link %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/forms.css' %}">
{% endblock %}

{% block content %}
    <h3 class="header-text mt-2 mb-5">Принять задание</h3>
    <div class="d-flex flex-column frame-bg my-2 p-2">
        <h4 class="main-text">Подготовленные модели</h4>
        <hr>
        {% include "Proccessing/predefined_model_from.html" %}
    </div>
    <div class="d-flex flex-column frame-bg my-5 p-2">
        <h4 class="main-text">Своя модель с <a href="https://huggingface.co/">Hugging Face</a></h4>
        <hr>
        <form method="post" id="task_from">{% csrf_token %}
            <h4 class="main-text">Дайте имя задаче:</h4>
            {% render_field form.name id="name" class="main-text" %}

            <h4 class="main-text">Выберите датасет:</h4>
            {% render_field form.dataset id="dataset_id" %}

            <h4 class="main-text">Внесите название модели:</h4>
            {% render_field form.model id="model_name" class="main-text" %}

            <h4 class="main-text">Укажите прочие параметры (<a href="{% url 'processing:guide' %}">где найти параметры и как их указать?</a>):</h4>
            {% render_field form.parameters_kv %}

            {% render_field form.parameters id="parameters" %}
            <br>
            <div class="d-flex justify-content-center my-2">
                <input id="task_send" class="btn btn-main main-text mb-1" type="submit" value="Отправить">
            </div>
        </form>
    </div>
    <script type="module" src="{% static 'js/processing/form_model_name.js' %}"></script>
{% endblock %}

AssrWeb/templates/Proccessing/guide.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <h3 class="header-text mb-5 mt-2">Руководство для применения произвольных моделей с <a href="https://huggingface.co/">Hugging Face</a></h4>
    <div class="main-text article-text my-2">
        <p>Большинство моделей можно применить, указав лишь их название. Однако, некоторые модели требуют указать дополнительные параметры, например токенизаторы или задачи (для мультимодальных моделей).</p>
        <p>На карточке модели следует обратить внимание на следующие параметры:</p>
        <ol>
            <li class="text-left">
                Название модели
                <img src="{% static 'img/guide/model_name.png' %}" class="my-2 article-image">
            </li>
            <li class="text-left">
                Задачу
                <img src="{% static 'img/guide/task.png' %}" class="my-2 article-image">
            </li>
            <li class="text-left">
                Токенизатор
                <img src="{% static 'img/guide/tokenizer.png' %}" class="my-2 article-image">
            </li>
            <li class="text-left">
                Прочие параметры, которые могут быть указаны в примере на странице модели
                <img src="{% static 'img/guide/extra.png' %}" class="my-2 article-image">
            </li>
        </ol>
        <p>Лишь имя модели является обязательным параметром и выделено в отдельное поле ввода. Остальные параметры являются опциональными и применяются, в основном, когда нужно скорректировать результат работы модели.</p>
        <p>Указывая дополнительные параметры модели, необходимо объявить ключ, соответствующий  типу параметра (например  task или tokenizer) и его значение без кавычек.</p>
        <img src="{% static 'img/guide/filled_out.png' %}" class="my-2 article-image">
        <p>Важно отметить, что часто код на Hugging Face приведён на языке программирования Python. Потому важно переводить значения истинности `True` и `False` в стандартные JSON значения `true` и `false`.</p>
    </div>
{% endblock %}

AssrWeb/templates/Proccessing/list.html
{% extends "base.html" %}
{% load static %}
{% load humanize %}

{% block link %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/forms.css' %}">
{% endblock %}

{% block content %}
    <h3 class="header-text mt-2 mb-5">Список заданий</h3>

    <div class="container-fluid d-flex flex-column">
        {% for task in task_list %}
            <div class="row container-fluid frame-bg my-2 p-2 rounded-pill">
                <a href="{% url 'processing:view' task.pk %}" class="main-text unlink darken-on-hover p-0">
                    <div class="row px-5">
                        <div class="col">Номер</div>
                        <div class="col">Название</div>
                        <div class="col">Датасет</div>
                        <div class="col">Модель</div>
                        <div class="col">Статус</div>
                        <div class="col">Время</div>
                    </div>
                </a>
                <hr>
                <div class="row px-5 main-text mini-text">
                    <div class="col"> <a href="{% url 'processing:view' task.pk %}"> {{task.pk}} </a> </div>
                    <div class="col"> <a href="{% url 'processing:view' task.pk %}"> {{task.name}} </a> </div>
                    <div class="col"><a href="{% url 'dataset:view_dataset' task.dataset.id %}">{{ task.dataset.id }}</a></div>
                    <div class="col">{{ task.model }}</div>
                    <div class="col">{{ task.get_status_display }}</div>
                    <div class="col">{{ task.creationTime|naturaltime }}</div>
                </div>
            </div>
        {% endfor %}
    </div>

    <div class="container-fluid d-flex justify-content-center">
        <h4>Страницы</h4>
    </div>
    <div class="container d-flex justify-content-center">
        {% if page_obj.has_previous %}
            <button class="frame-bg main-text"><a href="?page={{ page_obj.previous_page_number }}"> &lt;&lt; </a></button>
        {% endif %}
        <button disabled class="frame-bg main-text"> {{ page_obj.number }} </button>
        {% if page_obj.has_next %}
            <button class="frame-bg main-text"><a href="?page={{ page_obj.next_page_number }}"> &gt;&gt; </a></button>
        {% endif %}
    </div>
{% endblock %}

AssrWeb/templates/Proccessing/predefined_model_from.html
<div class="container-fluid">
    <div class="row">
        <div class="col">
            <select name="model_name" class="my-2" id="model_name_selector">
                <option disabled selected value>---------</option>
                <option disabled class="mb-2">
                    <a>___ Оценка тональности ___</a>
                </option>
                <option value="j-hartmann/emotion-english-distilroberta-base">
                    <a href="https://huggingface.co/j-hartmann/emotion-english-distilroberta-base">
                        emotion-english-distilroberta-base
                    </a>
                </option>
                <option value="tabularisai/multilingual-sentiment-analysis">
                    <a href="https://huggingface.co/tabularisai/multilingual-sentiment-analysis">
                        multilingual-sentiment-analysis
                    </a>
                </option>
                <option value="bhadresh-savani/bert-base-go-emotion">
                    <a href="https://huggingface.co/bhadresh-savani/bert-base-go-emotion">
                        bert-base-go-emotion
                    </a>
                </option>
                <option disabled class="mb-2">
                    <a>___ Извлечение именованных сущностей ___</a>
                </option>
                <option value="Babelscape/wikineural-multilingual-ner">
                    <a href="https://huggingface.co/Babelscape/wikineural-multilingual-ner">
                        wikineural-multilingual-ner
                    </a>
                </option>
                <option value="51la5/roberta-large-NER">
                    <a href="https://huggingface.co/51la5/roberta-large-NER">
                        roberta-large-NER
                    </a>
                </option>
                <option value="dslim/distilbert-NER">
                    <a href="https://huggingface.co/dslim/distilbert-NER">
                        distilbert-NER
                    </a>
                </option>
                <option disabled class="mb-2">
                    <a>___ Поиск ключевых слов ___</a>
                </option>
                <option value="yanekyuk/camembert-keyword-extractor">
                    <a href="https://huggingface.co/yanekyuk/camembert-keyword-extractor">
                        camembert-keyword-extractor
                    </a>
                </option>
                <option value="yanekyuk/bert-uncased-keyword-extractor">
                    <a href="https://huggingface.co/yanekyuk/bert-uncased-keyword-extractor">
                        bert-uncased-keyword-extractor
                    </a>
                </option>
                <option value="ilsilfverskiold/bart-keyword-extractor">
                    <a href="https://huggingface.co/ilsilfverskiold/bart-keyword-extractor">
                        bart-keyword-extractor
                    </a>
                </option>
            </select>
        </div>
    </div>
</div>

AssrWeb/templates/Proccessing/results.html
{% extends "base.html" %}
{% load static %}
{% block content %}
{% block link %}
    <input type="hidden" id="taskPk" value="{{ task_pk }}">
    <script src="https://d3js.org/d3.v5.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/mpld3@0.5.10/dist/mpld3.min.js"></script>
    <script src="{% static 'js/visualization/getFigures.js' %}"></script>
{% endblock %}
<h1>Задача: {{process.name}}<h1>
<h1>Обработка датасета <a href="{% url 'dataset:view_dataset' process.dataset.pk %}" > {{process.dataset.metadata.name}}</a> </h1>
<div class="status main-text">Задача создана: {{process.creationTime}}
<div class="status main-text">Статус задачи: 
        {% if process.status == '2' %} Успех ✓
        {% elif process.status == '3' %} Провал ⛔
        {% else %}Ожидание 🔥{% endif %}
</div>
<div class="mb-3">
    <a href="{% url 'processing:download' task_pk=task_pk %}?file_format=CSV" class="btn main-text btn-primary">
        Скачать CSV
    </a>
    <a href="{% url 'processing:download' task_pk=task_pk %}?file_format=JSON" class="btn main-text btn-primary">
        Скачать JSON
    </a>
</div>

{% if json_results %}
<div class="json-container" style="max-height: 700px;  max-width: 90%; overflow-y: auto; border: 1px solid #ccc; padding: 10px">
    <pre class="mb-0"><code>{{ json_results }}</code></pre>
</div>
{% else %}
<div class="alert alert-info">Результаты обработки ещё не готовы</div>
{% endif %}

<style>
    .card-header-text
    {
        color: #000000;
    }
    .card-body {
        position: relative;
        min-height: 600px;  
        height: 70vh; 
        overflow: auto;
        padding: 15px;
    }
    
    .mpl-container {
        width: 100% !important;
        height: 100% !important;
    }
    </style>
<div id="visualization-section" class="mt-4" 
     data-show-distribution="true">
    <h3>Визуализация результатов</h3>
    <select id="label-select" class="form-select mb-3" 
            style="max-width: 300px; display: none;">
        <option value="all">Все категории</option>
    </select>
<button id="static-btn" class="btn btn-secondary me-2">Показать статические графики</button>
<button id="interactive-btn" class="btn btn-info">Показать интерактивные графики</button>
<div id="figures-container" class="row mt-3"></div>

</div>
{% endblock %}