AssrWeb/CreateDatasetApp/urls.py
from django.urls import path
from CreateDatasetApp.views import *

app_name = "dataset"

urlpatterns = [
    path("new-dataset", create_view, name="new-source"),
    path("save", table_save_view, name="save"),
    path("table", table_view, name="table"),
    path("<int:dataset_pk>/save-source/", save_list_by_pk, name="save-source"),
    path("datasets-list", show_list, name="datasets-list"),
    # path(
    #     "datasets-list/<slug:dataset_slug>/",
    #     view_dataset,
    #     name="view_dataset"
    # ),
    path(
        "datasets-list/<slug:dataset_slug>/",
        Dataset_Details.as_view(),
        name="view_dataset"
    ),
    path("dataset-deletion/<slug:dataset_slug>/", delete_dataset, name='deletion'),
    path("datasets-list/<slug:dataset_slug>/edit_cell/", edit_cell, name="edit_cell"),
    path("datasets-list/<slug:dataset_slug>/remove_row/", remove_row, name="remove_row"),
    path("datasets-list/<slug:dataset_slug>/remove_column/", remove_column, name='remove_column'),
    path("datasets-list/<slug:dataset_slug>/import_from/", import_from, name="import_from"),
    path("datasets-list/<slug:dataset_slug>/new_line/", new_line, name="new_line"),
    path("datasets-list/<slug:dataset_slug>/remove_source/", delete_source, name="delete_source"),
    path("datasets-list/<slug:dataset_slug>/new_source/", new_source, name="new_source"),
    path("datasets-list/<slug:dataset_slug>/download/", dataset_download, name='dataset_download'),
    path("dataset/<slug:dataset_slug>/versions/", versions_list, name='versions_list'),
    path('version/<int:pk>/', version, name='version'),
    path('switch_version/<int:pk>/', switch_to_version, name='switch_to_version'),
    path("dataset/<slug:dataset_slug>/restore_init/", switch_to_init_version, name='restore_init'),
]

AssrWeb/DjangoAssr/urls.py
from django.urls import path, include
from django.contrib import admin
from UploadSource.views import list_page_view

urlpatterns = [
    path("", list_page_view, name="index"),
    path("source/", include("UploadSource.urls")),
    path("dataset/", include("CreateDatasetApp.urls")),
    path("processing/", include("ProcessingApp.urls")),
    path("visual/", include("Visual.urls")),
    path('admin/', admin.site.urls),
]

AssrWeb/ProcessingApp/urls.py
from django.urls import path

from ProcessingApp.views import (
    List_Result_View,
    Guide_view,
    AcceptTaskView,
    task_results,
    download_processing_results
)

app_name = "processing"

urlpatterns = [
    path("new-process/", AcceptTaskView.as_view(), name="new-process"),
    path("view/<slug:task_pk>/", task_results, name="view"),
    path("view/<slug:task_pk>/download/", download_processing_results, name="download"),
    path("tasks/", List_Result_View.as_view(), name="task-list"),
    path("guide/", Guide_view.as_view(), name="guide"),
]

AssrWeb/UploadSource/urls.py
from django.urls import path
from .views import (
    upload_page_view,
    upload_endpoint_view,
    filter_source_view,
    list_page_view,
    delete_view,
    search_source_by_string,
    Details_page,
)

app_name = "source"

urlpatterns = [
    path("new-source", upload_page_view, name="new-source"),
    path("source/search", search_source_by_string, name="search"),
    path("file", upload_endpoint_view, name="file-upload"),
    path("filter-source-list", filter_source_view, name="filter-source-list"),
    path("source-list", list_page_view, name="source-list"),
    path(
        "call-file/<int:metadata_id>",
        view=Details_page.as_view(),
        name="details"
    ),
    path("source-deletion/<int:metadata_id>", delete_view, name="delete"),
    path(
        "call-file/<int:metadata_id>",
        view=Details_page.as_view(),
        name="callajax"
    ),
]

AssrWeb/Visual/urls.py
from django.urls import path
from .api import visualization

app_name = "visual"

urlpatterns = [
    path(
        'results/<int:task_pk>/figures/',
        visualization.get_all_figures,
        name='get_figures'
    ),
    path(
        'results/<int:task_pk>/download-vis/',
        visualization.download_visualization,
        name='download-visualization'
    ),
]

AssrWeb/MetaCommon/models/metadata.py
from django.db import models
from django.core import validators
from .tags import Tags


class Metadata(models.Model):
    name = models.CharField(
        max_length=50,
        validators=[validators.MaxLengthValidator(50)]
    )

    author = models.CharField(
        max_length=50,
        null=True,
        validators=[validators.MaxLengthValidator(50)]
    )

    creationData = models.DateTimeField(
        auto_now_add=True,
        null=True,
        verbose_name='Дата создания'
    )

    keyValue = models.JSONField(null=True)
    tag = models.ManyToManyField(Tags)

    class Meta:
        abstract = True

    def __str__(self):
        return self.name

AssrWeb/templates/includes/fileUploadForm.html
{% load static %}

<form id="source-file-form" class="container-fluid frame-bg frame-pill pos-rel d-flex">
    <div class="container-fluid pos-rel frame-bg frame-h-3 px-0 w-50">
        <div class="pos-abs file-upload d-flex justify-content-center mt-2">
            <div class="container-fluid file-border d-flex flex-column justify-content-center">
                Перетащите файлы сюда (.csv, .pdf)
            </div>
        </div>
        <input type="file" id="source-files" class="pos-abs file-upload transparent" name="source-files" accept=".csv,.pdf" multiple>
    </div>
    
    <div class="pos-rel w-50">
        <div id="file-div" class="container-fluid d-flex flex-column pos-abs">
            
        </div>
    </div>

    <script type="module" src="{% static 'js/file/file_upload_form.js' %}"></script>
</form>

AssrWeb/templates/includes/listTemplate.html
{% load static %}
{% load widget_tweaks %}
{% block link %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/forms.css' %}">
  <script type="module" src="{% static 'js/core/tag_search.js' %}"></script>
{% endblock %}

<div class="search-page">
  <h1 class="header-text">{{page}}</h1>
  <form class="container-fluid frame-bg frame-pill" id="search-form" method="get">
      <div class="container-fluid d-flex flex-column px-2 py-2">
          <div class="container-fluid d-flex pos-rel mt-3">
              {{ form.search_query }}
              <input type="submit" class="btn btn-main main-text" type="button">
          </div>
          <div class="d-flex bd-highlight select-tags-cont">
            <div class="me-auto bd-highlight pos-rel mt-3" id="search-tags">
              <button class="btn btn-main main-text tag-list-button" type="button" data-bs-toggle="collapse" data-bs-target="#tag-list" aria-expanded="false" aria-controls="tag-list">
                Список тэгов
              </button>
              <div class="collapse" id="tag-list">
                {% render_field form.tag class="px-2 searchable-tag" %}
              </div>
            </div>
            <div class="flex-grow-1 d-flex mt-3 w-165" id="tags-list"></div>
          </div>
      </div>
  </form>
  <div class="tag-list">
  </div>
    <div class="pages-enum main-text">
      <h4 class="main-text">Страницы:</h4>
        {% if page_obj.has_other_pages %}
          <nav class="my-5">
            <ul class="pagination">
              {% if page_obj.has_previous %}
                <li class="page-item">
                  <a class="page-link main-text" href="?page=1">Первая</a>
                </li>
                <li class="page-item">
                  <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                    Предыдущая
                  </a>
                </li>
              {% endif %}
              {% for i in page_obj.paginator.page_range %}
                {% if page_obj.number == i %}
                  <li class="page-item active">
                    <span class="page-link">{{ i }}</span>
                  </li>
                {% else %}
                  <li class="page-item">
                    <a class="page-link" href="?page={{ i }}{% if request.GET.q %}&q={{ request.GET.search_query}}{% endif %}">{{ i }}</a>
                  </li>
                {% endif %}
              {% endfor %}
              {% if page_obj.has_next %}
                <li class="page-item">
                  <a class="page-link" href="?page={{ page_obj.next_page_number }}{% if request.GET %}&q={{ request.GET.search_query }}{% endif %}">
                    Следующая
                  </a>
                </li>
                <li class="page-item">
                  <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}{% if request.GET %}&q={{ request.GET.search_query }}{% endif %}">
                    Последняя
                  </a>
                </li>
              {% endif %}
            </ul>
          </nav>
        {% endif %}
    </div>
    <div class = "content-list">
        <div class="list-of-elements">
            <div class="list-element-container"  id="addition-element">
                <a class="list-element-link" id="addition-element-link" href="{% url addition_link %} ">+{{create_name}}</a>
            </div>
                {% for object in page_obj %}
            <div class="list-element-container">
                {% if processes %}
                <a class="list-element-link" href="{% url link object.pk %}">  Процесс для {{ object.dataset.metadata.name }} </a>
                <div class="status main-text" > {{ object.model}} </div>
                <div class="status main-text">Статус задачи: 
                  {% if object.status == '2' %} Успех
                  {% elif object.status == '3' %} Провал
                  {% else %}Ожидание{% endif %}
                </div>
                <label class="date-of-creation main-text">Создан:{{object.creationTime}}</label>
                <label class="authors main-text">Автор: {{object.dataset.author}}</label>
                <div class="tags-list-in-list-element">
                    <label class="description main-text">Ключи: {{object.dataset.keyValue}}</label>
                </div>
                <div class="tags-list-in-list-element ">Тэги:
                    {% for tag in object.dataset.tag.all %}
                    <label class="main-text deletable-tag tag-element">{{tag.name}}</label>
                    {% endfor %}
                </div>
                {% else %}
                <a class="list-element-link" href="{% url  link  object.pk %} ">{{object.name}}</a>
                <label class="date-of-creation main-text">Создан:{{object.creationData}}</label>
                <label class="authors main-text">Автор: {{object.author}}</label>
                <div class="tags-list-in-list-element">
                    <label class="description main-text">Ключи: {{object.keyValue}}</label>
                </div>
                <div class="tags-list-in-list-element ">Тэги:
                    {% for tag in object.tag.all %}
                    <label class="main-text deletable-tag tag-element">{{tag.name}}</label>
                    {% endfor %}
                </div>
                {% endif %}
                
            </div>
            {% endfor %}
        </div>
    </div>
</div>

AssrWeb/templates/includes/metadataForm.html
{% load widget_tweaks %}
{% load static %}

<form class="container-fluid frame-bg frame-pill">
    <div class="container-fluid d-flex flex-column px-2 py-2">

        <div class="container-fluid d-flex justify-content-left my-1">
            <label class="w-25" for="{{metadataForm.name.id_for_label}}">Название: </label>
            {% render_field metadataForm.name class="w-50 main-text" %}
        </div>

        <div class="container-fluid d-flex justify-content-left my-1">
            <label class="w-25" for="{{metadataForm.author.id_for_label}}">Автор: </label>
            {% render_field metadataForm.author class="w-50 main-text" %}
        </div>

        <div class="container-fluid d-flex flex-column my-1">
            <label for="{{metadataForm.keyValue.id_for_label}}">Прочие свойства: </label>
            <div class="pos-rel kv-overflow">
                {% render_field metadataForm.keyValue class="w-100 main-text frame-b" %}
            </div>
        </div>
        
        <div class="container-fluid d-flex flex-column my-1">
            <label for="tag-list">Тэги: </label>
            <div class="container-fluid d-flex justify-content-between">
                <div class="container-fluid pos-rel">
                    <button class="btn btn-main main-text w-100" type="button" data-bs-toggle="collapse" data-bs-target="#tag-list" aria-expanded="false" aria-controls="tag-list">
                        Показать список тэгов
                    </button>
                    <div class="collapse" id="tag-list">
                        {% render_field metadataForm.tag class="px-2" %}
                    </div>
                </div>
                <div class="container-fluid d-flex justify-content-between">
                    <input class="w-60 main-text mx-1" type="text" name="new-tag" id="new-tag" placeholder="Новый тэг">
                    <button id="create-tag" class="btn btn-main main-text w-40" type="button">
                        Создать
                    </button>
                </div>
            </div>
        </div>
    </div>
</form>

AssrWeb/templates/includes/navbar.html
<nav id="sidebar">
    <div class="sidebar-header my-4 d-flex justify-content-center" id="logo">
        <h3 class="header-text my-4">ALAS</h3>
    </div>
    <ul class="list-unstyled navbar-nav">
        <li class="nav-item active align-center my-2">
            <a class="nav-link main-text" href="{% url 'dataset:datasets-list' %}">Датасеты</a>
        </li>
        <li class="nav-item align-center my-2">
            <a class="nav-link main-text" href="{% url 'dataset:new-source' %}">Создать датасет</a>
        </li>
        <li class="nav-item align-center my-2">
            <a class="nav-link main-text" href="{% url 'source:source-list' %}">Файлы-исходники</a>
        </li>
        <li class="nav-item align-center my-2">
            <a class="nav-link main-text" href="{% url 'source:new-source' %}">Загрузить файл-исходник</a>
        </li>
        <li class="nav-item align-center my-2">
            <a class="nav-link main-text" href="{% url 'processing:new-process' %}">Начать обработку</a>
        </li>
        <li class="nav-item align-center my-2">
            <a class="nav-link main-text" href="{% url 'processing:task-list' %}">Задачи обаботки</a>
        </li>
    </ul>
</nav>

AssrWeb/templates/includes/sourceListTable.html
<table class="w-100 main-text frame-b">
    <tr class="frame-b">
        <td class="frame-b px-2">Выбор</div>
        <td class="frame-b px-2">Название</div>
        <td class="frame-b px-2">Автор</div>
        <td class="frame-b px-2">Тэги</div>
    </tr>
    {% for source in source_files %}
        <tr class="frame-b">
            <td class="frame-b">
                <div class="d-flex justify-content-center">
                    <input type="checkbox" name="dataset_select" data-pk="{{source.pk}}" class="large-checkbox checkbox-handler-select" id="dataset_{{source.pk}}" {% if source.checked %}checked{% endif %}>
                </div>
            </td>
            <td class="frame-b">
                <label for="dataset_{{source.pk}}">
                    {{source.metadata.name|truncatechars:30}}
                </label>
            </td>
            <td class="frame-b">
                <label for="dataset_{{source.pk}}">
                    {{source.metadata.author|truncatechars:30}}
                </label>
            </td>
            <td class="frame-b">
                <label for="dataset_{{source.pk}}">
                    {% if source.metadata.tag.all %}
                        {{source.metadata.tag.all|join:"; "|truncatechars:30}}
                    {% endif %}
                </label>
            </td>
            <td class="frame-b">
                <a href="{% url 'source:details' source.pk %}">👁</a>
            </td>
            {% if object.pk  %}
                <td class="frame-b">
                    {% if source.checked %}
                        <form action="{% url 'dataset:delete_source' object.pk %}" method="post" style="display: inline;">
                            {% csrf_token %}
                            <input type="hidden" name="source_file_pk" value="{{ source.pk }}">
                            <button type="submit" class="link-button">🗑</button>
                        </form>
                    {% else %}
                    <form action="{% url 'dataset:new_source' object.pk %}" method="post" style="display: inline;">
                        {% csrf_token %}
                        <input type="hidden" name="source_file_pk" value="{{ source.pk }}">
                        <button type="submit" class="link-button">&#43</button>
                    </form>
                    {% endif %}    
                </td>
            {% endif %}
        </tr>
    {% endfor %}
    <tr>
        <td colspan="4">
            <div class="d-flex justify-content-evenly my-1  ">
                {% if source_files.has_previous %}
                    <div>
                        <button type="button" class="source-search-button btn btn-main main-text" data-page="{{ source_files.previous_page_number }}">
                            прошлая страница
                        </button>
                    </div>
                {% endif %}
                {% if source_files.has_next %}
                    <div>
                        <button type="button" class="source-search-button btn btn-main main-text" data-page="{{ source_files.next_page_number }}">
                            следующая страница
                        </button>
                    </div>
                {% endif %}
            </div>
        </td>
    </tr>
</table> 

AssrWeb/templates/includes/sourceListView.html
{% load static %}

<form id="source-file-form" class="container-fluid frame-bg frame-pill pos-rel d-flex flex-column frame-h-6 pos-rel">
    <div class="container-fluid w-100 d-flex justify-content-between mt-2">
        <input type="text" name="search_source" class="w-75 main-text" id="search_source" placeholder="Поиск по файлам">
        <button type="submit" disabled style="display: none" aria-hidden="true"></button>
        <button type="button" class="btn btn-main w-25 main-text" id="source-search-button-id" data-page="0">Найти</button>
    </div>
</form>
    <div class="container-fluid w-100 my-2 overflow-y" id="source-table">
        {% include "includes/sourceListTable.html" %}
    </div>
    <script type="module" src="{% static 'js/dataset/dataset_form.js' %}"></script>